// UI_ACTIONS
export const SIDER_COLLAPSED = 'SIDER_COLLAPSED';


// COUNTER_ACTIONS
export const SYNC_INCREMENT_COUNTER = 'SYNC_INCREMENT_COUNTER';
export const SYNC_DECREMENT_COUNTER = 'SYNC_DECREMENT_COUNTER';
export const ASYNC_INCREMENT_COUNTER = 'ASYNC_INCREMENT_COUNTER';
export const ASYNC_DECREMENT_COUNTER = 'ASYNC_DECREMENT_COUNTER';

export const TOGGLE_ASYNC_INCREMENT_LOADING = 'TOGGLE_ASYNC_INCREMENT_LOADING';
export const TOGGLE_ASYNC_DECREMENT_LOADING = 'TOGGLE_ASYNC_DECREMENT_LOADING';

// TODOS_ACTIONS
export const ADD_TODO = 'ADD_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const FILTER_TODO = 'FILTER_TODO';
export const SHOW_ALL = 'SHOW_ALL';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';
export const SHOW_ACTIVE = 'SHOW_ACTIVE';
